// Generated by gencpp from file webots_demo/Goalname.msg
// DO NOT EDIT!


#ifndef WEBOTS_DEMO_MESSAGE_GOALNAME_H
#define WEBOTS_DEMO_MESSAGE_GOALNAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webots_demo
{
template <class ContainerAllocator>
struct Goalname_
{
  typedef Goalname_<ContainerAllocator> Type;

  Goalname_()
    : goal_name()  {
    }
  Goalname_(const ContainerAllocator& _alloc)
    : goal_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _goal_name_type;
  _goal_name_type goal_name;





  typedef boost::shared_ptr< ::webots_demo::Goalname_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webots_demo::Goalname_<ContainerAllocator> const> ConstPtr;

}; // struct Goalname_

typedef ::webots_demo::Goalname_<std::allocator<void> > Goalname;

typedef boost::shared_ptr< ::webots_demo::Goalname > GoalnamePtr;
typedef boost::shared_ptr< ::webots_demo::Goalname const> GoalnameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webots_demo::Goalname_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webots_demo::Goalname_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::webots_demo::Goalname_<ContainerAllocator1> & lhs, const ::webots_demo::Goalname_<ContainerAllocator2> & rhs)
{
  return lhs.goal_name == rhs.goal_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::webots_demo::Goalname_<ContainerAllocator1> & lhs, const ::webots_demo::Goalname_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace webots_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::webots_demo::Goalname_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webots_demo::Goalname_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_demo::Goalname_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_demo::Goalname_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_demo::Goalname_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_demo::Goalname_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webots_demo::Goalname_<ContainerAllocator> >
{
  static const char* value()
  {
    return "254bb0d4018de3d871badc783fa8b12a";
  }

  static const char* value(const ::webots_demo::Goalname_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x254bb0d4018de3d8ULL;
  static const uint64_t static_value2 = 0x71badc783fa8b12aULL;
};

template<class ContainerAllocator>
struct DataType< ::webots_demo::Goalname_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webots_demo/Goalname";
  }

  static const char* value(const ::webots_demo::Goalname_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webots_demo::Goalname_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string goal_name\n"
;
  }

  static const char* value(const ::webots_demo::Goalname_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webots_demo::Goalname_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goalname_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webots_demo::Goalname_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webots_demo::Goalname_<ContainerAllocator>& v)
  {
    s << indent << "goal_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goal_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBOTS_DEMO_MESSAGE_GOALNAME_H
