###########################################################################################
## NOTE: Costmap conversion is experimental. Its purpose is to combine many point        ##
## obstales into clusters, computed in a separate thread in order to improve the overall ## 
## efficiency of local planning. However, the implemented conversion algorithms are in a ##
## very early stage of development. Contributions are welcome!                           ##
###########################################################################################

TebLocalPlannerROS:
  ## Costmap converter plugin   
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
 
 
  ## Configure plugins (namespace move_base/costmap_to_lines or move_base/costmap_to_polygons)
  ## costmap_converter/CostmapToLinesDBSRANSAC, costmap_converter/CostmapToLinesDBSMCCH, costmap_converter/CostmapToPolygonsDBSMCCH
  costmap_converter/CostmapToPolygonsDBSMCCH:
    # 对障碍的最大距离
    cluster_max_distance: 0.4
    # 定义一个簇的最少点数
    cluster_min_pts: 2
    # 定义一个簇的最多点数
    cluster_max_pts: 30
    # 清除凸多边形彼此靠近的关键点/顶点
    convex_hull_min_pt_separation: 0.1
  
  costmap_converter/CostmapToLinesDBSMCCH:
    cluster_max_distance: 0.1
    cluster_min_pts: 2
    cluster_max_pts: 30
    convex_hull_min_pt_separation: 0.1
    # 从点到要计算为支撑点的线的最小距离
    support_pts_max_dist: 0.3
    # 如果两个连续的支撑点少于这个阈值，那只定义一条线，设置成0则停用此检查
    support_pts_max_dist_inbetween: 0.3
    # 需要表示成线的最少支撑点数
    min_support_pts: 2

  costmap_converter/CostmapToLinesDBSRANSAC:
    # 对障碍的最大距离
    cluster_max_distance: 0.3
    # 定义一个簇的最少点数
    cluster_min_pts: 2
    ransac_inlier_distance: 0.15
    ransac_min_inliers: 10
    ransac_no_iterations: 1500
    ransac_remainig_outliers: 3
    ransac_convert_outlier_pts: True
    ransac_filter_remaining_outlier_pts: False
    convex_hull_min_pt_separation: 0.1
 
